# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'explorer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setStyleSheet("background-color: rgb(0, 40, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_tree = QtWidgets.QTreeView(self.centralwidget)
        self.file_tree.setGeometry(QtCore.QRect(20, 110, 560, 300))
        self.file_tree.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.file_tree.setObjectName("file_tree")
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(20, 20, 560, 31))
        self.path.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Dubai\";")
        self.path.setInputMask("")
        self.path.setText("")
        self.path.setObjectName("path")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(480, 60, 101, 41))
        self.btn_open.setStyleSheet("background-color: rgb(15, 80, 24);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 13pt \"Dubai\";")
        self.btn_open.setObjectName("btn_open")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(20, 430, 560, 20))
        self.status.setStyleSheet("color: rgb(0, 120, 0);")
        self.status.setObjectName("status")
        self.btn_root_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_root_up.setGeometry(QtCore.QRect(60, 80, 35, 25))
        self.btn_root_up.setStyleSheet("background-color: rgb(15, 80, 24);")
        self.btn_root_up.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("static/arrow_upward_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_root_up.setIcon(icon)
        self.btn_root_up.setObjectName("btn_root_up")
        self.btn_root_next = QtWidgets.QPushButton(self.centralwidget)
        self.btn_root_next.setGeometry(QtCore.QRect(100, 80, 35, 25))
        self.btn_root_next.setStyleSheet("background-color: rgb(15, 80, 24);")
        self.btn_root_next.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("static/arrow_forward_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_root_next.setIcon(icon1)
        self.btn_root_next.setObjectName("btn_root_next")
        self.wallpaper = QtWidgets.QLabel(self.centralwidget)
        self.wallpaper.setGeometry(QtCore.QRect(0, -20, 761, 551))
        self.wallpaper.setText("")
        self.wallpaper.setPixmap(QtGui.QPixmap("static/clever.jpg"))
        self.wallpaper.setObjectName("wallpaper")
        self.btn_root_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_root_reset.setGeometry(QtCore.QRect(20, 80, 35, 25))
        self.btn_root_reset.setStyleSheet("background-color: rgb(15, 80, 24);")
        self.btn_root_reset.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("static/autorenew_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_root_reset.setIcon(icon2)
        self.btn_root_reset.setObjectName("btn_root_reset")
        self.btn_root_home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_root_home.setGeometry(QtCore.QRect(140, 80, 35, 25))
        self.btn_root_home.setStyleSheet("background-color: rgb(15, 80, 24);")
        self.btn_root_home.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("static/home_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_root_home.setIcon(icon3)
        self.btn_root_home.setObjectName("btn_root_home")
        self.btn_toggle_hidden = QtWidgets.QPushButton(self.centralwidget)
        self.btn_toggle_hidden.setGeometry(QtCore.QRect(180, 80, 35, 25))
        self.btn_toggle_hidden.setStyleSheet("background-color: rgb(15, 80, 24);")
        self.btn_toggle_hidden.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("static/eye_tracking_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toggle_hidden.setIcon(icon4)
        self.btn_toggle_hidden.setObjectName("btn_toggle_hidden")
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(220, 80, 35, 25))
        self.btn_search.setStyleSheet("background-color: rgb(15, 80, 24);")
        self.btn_search.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("static/search_24dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon5)
        self.btn_search.setObjectName("btn_search")
        self.wallpaper.raise_()
        self.file_tree.raise_()
        self.path.raise_()
        self.btn_open.raise_()
        self.status.raise_()
        self.btn_root_up.raise_()
        self.btn_root_next.raise_()
        self.btn_root_reset.raise_()
        self.btn_root_home.raise_()
        self.btn_toggle_hidden.raise_()
        self.btn_search.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Explorer QT"))
        self.btn_open.setText(_translate("MainWindow", "Открыть"))
        self.status.setText(_translate("MainWindow", "status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
